name: Idee of verbetering
description: Stel een nieuwe functie of verbetering voor
labels: [enhancement]
body:
  - type: textarea
    id: idee
    attributes:
      label: Wat zou je willen?
      description: Beschrijf de functie of verbetering en waarvoor je die nodig hebt.
    validations:
      required: true
  - type: textarea
    id: alternatief
    attributes:
      label: Alternatieven
      description: Zijn er work-arounds of andere oplossingen die je hebt overwogen?
